jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8001
   servlet:
      # context-path: /clientes
      session:
         timeout: 21600s
springdoc:
   swagger-ui:
      path: /swagger-ui.html
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/ceiba_adn_clientes?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      hikari:
         poolName: pool
   application:
      name: servicioClientes
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest


eureka:
   instance:
      hostname: localhost
      preferIpAddress: true
   client:
      enabled: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/

management:
   security:
      enabled: false
   endpoint:
      health:
         enabled: true
         show-details: always
   endpoints:
      jmx:
         exposure:
            include: '*'
      web:
         exposure:
            include: '*'
         base-path: /actuator
         cors:
            allowed-origins: true

feign:
   circuitbreaker:
      enabled: true

hystrix:
   dashboard:
      proxy-stream-allow-list: '*'

# servicioClientes:
#    ribbon:
#       eureka:
#          enabled: false
#       listOfServers: localhost:${server.port}
#       ServerListRefreshInterval: 15000

