server:
   port: 8080

eureka:
   instance:
      hostname: localhost
      preferIpAddress: true
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/

spring:
   application:
      name: servicioEnrutacion  
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
         routes:
         -  id: servicioClientes
            uri: lb://servicioClientes
            predicates:
               -  Path=/clientes/**

         -  id: servicioContratos
            uri: lb://servicioContratos
            predicates:
               - Path=/contratos/**,/clientes/**

management:
  endpoints:
    web:
      exposure:
        include: '*'



